import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:forui/forui.dart';

import '../../../../core/config/theme/app_theme.dart';
import '../../../../core/constants/app_constants.dart';
import '../../../projects/presentation/providers/project_provider.dart';
import '../../../tasks/presentation/providers/task_provider.dart';
import '../../domain/entities/focus_session.dart';
import '../../domain/entities/session_state.dart';
import '../providers/focus_session_provider.dart';

class FocusSessionScreen extends ConsumerWidget {
  const FocusSessionScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final session = ref.watch(focusTimerProvider);

    if (session == null) {
      return const FScaffold(child: Center(child: Text('No active session')));
    }

    // These will be generated by build_runner
    final taskAsync = ref.watch(taskByIdProvider(session.taskId.toString()));

    return FScaffold(
      header: FHeader.nested(
        title: const Text('Focus'),
        prefixes: [
          FHeaderAction.back(onPress: () => Navigator.of(context).pop()),
        ],
      ),
      child: Center(
        child: Padding(
          padding: EdgeInsets.all(AppConstants.spacing.large),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              taskAsync.when(
                data: (task) {
                  final projectAsync = ref.watch(
                    projectByIdProvider(task.projectId.toString()),
                  );
                  return Column(
                    children: [
                      Text(
                        task.title,
                        style: context.typography.xl2.copyWith(
                          fontWeight: FontWeight.w600,
                        ),
                        textAlign: TextAlign.center,
                      ),
                      const SizedBox(height: 4),
                      projectAsync.when(
                        data: (project) => Text(
                          project?.title ?? '',
                          style: context.typography.base.copyWith(
                            color: context.colors.mutedForeground,
                          ),
                        ),
                        loading: () => const SizedBox.shrink(),
                        error: (_, _) => const SizedBox.shrink(),
                      ),
                    ],
                  );
                },
                loading: () => const SizedBox.shrink(),
                error: (_, _) => const Text('Error loading task'),
              ),
              const Spacer(flex: 2),
              _TimerDisplay(session: session),
              const Spacer(flex: 3),
              _FocusControls(session: session),
            ],
          ),
        ),
      ),
    );
  }
}

class _TimerDisplay extends StatelessWidget {
  final FocusSession session;

  const _TimerDisplay({required this.session});

  @override
  Widget build(BuildContext context) {
    final isFocus =
        session.state == SessionState.running ||
        session.state == SessionState.paused;
    final totalSeconds = isFocus
        ? session.focusDurationMinutes * 60
        : session.breakDurationMinutes * 60;

    final elapsedInPhase = isFocus
        ? session.elapsedSeconds
        : session.elapsedSeconds - (session.focusDurationMinutes * 60);

    final remainingSeconds = totalSeconds - elapsedInPhase;
    final minutes = (remainingSeconds / 60).floor();
    final seconds = remainingSeconds % 60;

    final progress = (elapsedInPhase / totalSeconds).clamp(0.0, 1.0);

    return Column(
      children: [
        Text(
          isFocus ? 'Focus Mode' : 'Break Time',
          style: context.typography.sm.copyWith(
            color: context.colors.primary,
            fontWeight: FontWeight.w600,
            letterSpacing: 2.0,
          ),
        ),
        const SizedBox(height: 24),
        Text(
          '${minutes.toString().padLeft(2, '0')}:${seconds.toString().padLeft(2, '0')}',
          style: context.typography.xl7.copyWith(
            fontWeight: FontWeight.w100,
            fontSize: 80, // Extra large for impact
          ),
        ),
        const SizedBox(height: 48),
        SizedBox(
          width: 240,
          child: Column(
            children: [
              LinearProgressIndicator(
                value: progress,
                backgroundColor: context.colors.border,
                color: context.colors.primary,
                minHeight: 2, // Minimalist thin line
              ),
            ],
          ),
        ),
      ],
    );
  }
}

class _FocusControls extends ConsumerWidget {
  final FocusSession session;

  const _FocusControls({required this.session});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final notifier = ref.read(focusTimerProvider.notifier);
    final isRunning =
        session.state == SessionState.running ||
        session.state == SessionState.onBreak;
    final isPaused = session.state == SessionState.paused;

    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        if (isPaused)
          FButton(
            onPress: () => notifier.resumeSession(),
            child: const Text('Resume'),
          )
        else if (isRunning)
          FButton(
            onPress: () => notifier.pauseSession(),
            child: const Text('Pause'),
          ),
        const SizedBox(width: 16),
        FButton(
          style: FButtonStyle.ghost(),
          onPress: () => _confirmCancel(context, notifier),
          child: Icon(FIcons.x),
        ),
      ],
    );
  }

  void _confirmCancel(BuildContext context, dynamic notifier) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('End focus?'),
        content: const Text('Your progress will be lost.'),
        actions: [
          FButton(
            style: FButtonStyle.ghost(),
            onPress: () => Navigator.pop(context),
            child: const Text('Keep going'),
          ),
          FButton(
            style: FButtonStyle.destructive(),
            onPress: () {
              notifier.cancelSession();
              Navigator.pop(context);
              Navigator.pop(context);
            },
            child: const Text('End session'),
          ),
        ],
      ),
    );
  }
}
